version: '3.8'

services:
  web:
    build: .
    image: chatroomapp:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=chatuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_DB=chatroomdb
    volumes:
      - ./db.yaml:/app/db.yaml
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatroomdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  nginx:
    image: nginx:1.26
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always

volumes:
  mysql-data: